// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyiwvkvtfkhibdhimypq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aXd2a3Z0ZmtoaWJkaGlteXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTkwMTAsImV4cCI6MjA1MDE5NTAxMH0.6fR4sotcQbn4cA6S5ZBlSfSd4ZXlc1Q7L20Xtyr6P4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);